spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${SPRING_DATA_URL}
    password: ${SPRING_DATA_PASS}
    username: ${SPRING_DATA_USER}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

server:
  port: 0

jwt:
  secret-key: .dmdjgroet7478#$%^&*risrweriu;we84334

