server:
  port: 8080

jwt:
  secret-key: .dmdjgroet7478#$%^&*risrweriu;we84334

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway

  # Connect to Reactive Redis instance
  data:
    redis:
      host: ${SPRING_REDIS_URL_HOST}
      port: ${SPRING_REDIS_URL_PORT}
      password: ${SPRING_REDIS_URL_PASSWORD}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: ${ALLOW_ORIGIN}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"

          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: url-service-generate
              uri: lb://URL-SERVICE
              predicates:
                - Path=/generate
              filters:
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@redisRateLimiter}"
                    key-resolver: "#{@simpleClientAddressResolver}"
                - name: TokenRelayHeaderFilter

            - id: url-service-redirect
              uri: lb://URL-SERVICE
              predicates:
                - Path=/getUrl/**
              filters:
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@redisRateLimiter}"
                    key-resolver: "#{@simpleClientAddressResolver}"

            - id: csv-data
              uri: lb://URL-SERVICE
              predicates:
                - Path=/upload/csv
              filters:
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@redisRateLimiter}"
                    key-resolver: "#{@simpleClientAddressResolver}"

allow:
  origins: ${ALLOW_ORIGIN}
